### ISSUE TITLE
[REQUEST] Change test screen colors

### ISSUE THREAD

**Issue by Arakon** [TeamOpenFIRE/OpenFIRE-App#26]
I'm aware this is a fairly minor issue for most people, but in my case I just spent 30 mins trying to figure out why none of the buttons in the test button screen worked, until my wife pointed out that they do. I'm partially color blind and it's nearly impossible for me to see the thin text changing to red when a button is pressed. If a more prominent color could be used here, or the background of the field changed instead of the text, that would be a great help.

**Comment by SeongGino** [comment]
Apologies for your visual impairment. The color is just a flat intensity red, which *should* be balanced for both light and dark mode setups without blending in to the window geometry too much.

This is a test build with the label boxes being colored rather than the text itself. How does this look for you? (GH apparenty isn't showing embeds properly :< )
Dark mode on Linux: https://github.com/user-attachments/assets/020548e6-ae33-4f9b-a517-056e3716a608

Light mode on Windows 10: https://github.com/user-attachments/assets/215b986b-5589-4bde-8222-5479331134cb

**Comment by Arakon** [comment]
That works great for me, very clear indication that the button is being pressed. Thanks for looking into this so quickly!

**Comment by SeongGino** [comment]
Glad to hear! It was a change that only took a few seconds, really. But there's a couple more spots related to stylesheets that could use some work in the main file, so I'll clean things up a bit more before pushing this change here.
